### ISSUE TITLE
Rework on Weighted Power

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/StravaPlus#19]
**Task list**

- [x] Detect power meter or not: add "hasPowerMeter" in "VacuumProcessor.getActivityStream" callback
- [x] If power meter then use Strava Weighted Power Value (catch it in activity Stats Map).
- [x] If power meter do not display Weighted Power Value in S+ extended data grid
- [x] If NO power meter then compute Estimated Weighted Power Value
- [x] Finally rename to Weighted Power instead of harmonized/normalized power
- [x] Update Hints

**Comment by thomaschampagne** [comment]
Activities example with power meter:
https://www.strava.com/activities/253876334
https://www.strava.com/activities/247943026
