### ISSUE TITLE
User can choose speed or pace display inside extended stats

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/StravaPlus#46]
**Todo**
- [ ] Add pace option
- [ ] Add pace settings page (same as speed but pace :))
- [ ] Genuine Avg Pace

**Comment by gmucha** [comment]
Also - add pace zones configured similarily to HR zones (though this overlaps with Strava Premium functionality)
